### PR TITLE
Use pipe fail, quote array expansion and prevent word globbing

### PR DESCRIPTION
**Pull request by fredclausen**
The previous PRs failed to build because hadolint was mad. I think this fixes the problem but I'm curious about unintended side affects.

### CODE REVIEW

**Comment by fredclausen** [comment]
@wiedehopf

**Comment by wiedehopf** [comment]
Hmmm it would seems the PRs don't run the build automatically otherwise i would have seen this i think?

The changes in this PR seem fine to me.

**Comment by fredclausen** [comment]
We are wildly inconsistent with requiring hadolint/other linters before building/merging, as well as the kinds/types of builds we do on PRs.

I've added a pr flow to this PR and it's unhappy about something. I can't diagnose now, but I'll see what it doesn't like as soon as I can.

**Comment by wiedehopf** [comment]
This seems to be showing errors for the state before your last commit.
Possibly because of when you requested the review?

Might need to re-request the review on the current state.

**Comment by fredclausen** [comment]
Yeah I think the error was the original commit + my commit with the PR build action. The fix in the last commit seems to have fixed it. I'll do a local test build soon to make sure the build isn't broken before I merge in, but when I build it on my laptop it looks like it's doing everything right.

**Comment by wiedehopf** [comment]
local build of this branch works fine.

**Comment by fredclausen** [comment]
I'll merge it then :) Thanks @wiedehopf

**Pull request merged**
